#!/bin/bash
/bin/mkdir -p /storage/Services ;
/usr/bin/mfsmount /mnt/MFS -H mfs.barton.ac.uk -o allow_other -o ro ;
/usr/bin/rsync -ravh --update --progress /mnt/MFS/Services/imagr /storage/Services/ ;
/usr/sbin/service nginx start ;
